insert into public.services
(name,slug,description,base_price,category,service_type,unit,market_price,is_add_on,frequency,bundle_services)
values
('Standard Airbnb Turnover','standard-airbnb','Complete guest turnover cleaning: dust all surfaces, vacuum/mop floors, sanitize bathrooms & kitchen, empty trash, make beds with fresh linens, restock basic amenities',32,'residential','cleaning','job',35,false,null,'{}'),
('Deep Clean','deep-clean','Comprehensive deep cleaning: baseboards, window sills, inside appliances, ceiling fans, light fixtures, detailed bathroom scrubbing, kitchen cabinet fronts, door frames',42,'residential','cleaning','job',45,false,null,'{}'),
('Move-In/Move-Out Clean','move-clean','Intensive cleaning for property transitions: inside cabinets/drawers, appliance interiors, wall spot cleaning, minor maintenance checks, detailed inspection report',36,'residential','cleaning','job',38,false,null,'{}'),
('Room Add-Ons','room-addon','Targeted room enhancement: extra bathroom deep clean, kitchen appliance detailing, balcony/patio cleaning, closet organization, premium room refresh',13,'residential','cleaning','room',15,true,null,'{}'),
('Window Cleaning','window-clean','Professional interior window cleaning: streak-free glass, window sills, frames, mirrors, glass doors, improved natural light and guest experience',40,'residential','cleaning','job',45,false,null,'{}'),
('Laundry & Ironing','laundry','Complete laundry service: wash, dry, fold bed linens and towels, iron as needed, quality fabric care, fresh scent treatment, same-day turnaround',28,'residential','restocking','load',30,false,null,'{}'),
('Supplies Restocking','supplies-restock','Guest amenity restocking: toilet paper, towels, soap, shampoo, coffee, tea, cleaning supplies, welcome snacks, quality brand selection',14,'residential','restocking','job',16,false,null,'{}'),
('Eco-Friendly Cleaning','eco-clean','Green cleaning with certified non-toxic products: plant-based cleaners, biodegradable supplies, allergen-free environment, safe for children and pets',55,'specialty','cleaning','job',null,false,null,'{}'),
('Pet-Friendly Deep Clean','pet-clean','Specialized pet cleanup: fur removal, odor elimination, pet-safe sanitizers, upholstery treatment, air purification, allergy-conscious cleaning',60,'specialty','cleaning','job',null,false,null,'{}'),
('Room-By-Room Premium Add-On','premium-addon','Luxury enhancement service: antimicrobial treatment, high-touch surface sanitization, premium air freshening, detailed quality inspection',20,'specialty','cleaning','room',null,true,null,'{}'),
('Light Office Cleaning','light-office','Weekly office maintenance for 2,500 sq ft: desk cleaning, trash removal, restroom sanitization, common area tidying, professional appearance',350,'commercial','cleaning','sqft',null,false,'monthly','{}'),
('Standard Office Cleaning','standard-office','Bi-weekly comprehensive cleaning for 3,500 sq ft: vacuum/mop, kitchen cleaning, conference room setup, detailed restroom service, supply monitoring',600,'commercial','cleaning','sqft',null,false,'monthly','{}'),
('Emergency Disinfection','emergency-disinfect','Rapid response sanitization: hospital-grade disinfection, high-touch surface treatment, air purification, health compliance certification',45,'commercial','cleaning','hour',null,false,null,'{}'),
('Restock & Consumables','office-restock','Weekly office supply management: paper products, cleaning supplies, kitchen items, hand sanitizer, quality brand selection, inventory tracking',25,'commercial','restocking','job',null,false,'weekly','{}'),
('Minor Repairs & Pre-Inspection','minor-repairs','Property maintenance check: light bulb replacement, handle tightening, leak detection, smoke alarm testing, detailed defect reporting, preventive care',25,'maintenance','repair','job',null,false,null,'{}'),
('Smart Home Setup','smart-home','Technology installation service: smart locks, thermostats, WiFi optimization, guest instruction cards, remote monitoring setup, tech support',50,'maintenance','maintenance','job',null,false,null,'{}'),
('Seasonal Pool & Lawn Care','pool-lawn','Weekly outdoor maintenance: pool cleaning/chemical balance, lawn mowing, hedge trimming, patio cleaning, seasonal plant care, curb appeal enhancement',175,'maintenance','maintenance','job',null,false,'monthly','{}'),
('Essential Airbnb Bundle','essential-bundle','Complete guest turnover package: standard cleaning, fresh linens, amenity restocking, basic maintenance check, guest-ready guarantee, same-day service',45,'bundle','cleaning','job',null,false,null,array['standard-airbnb','supplies-restock']),
('Premium Airbnb Bundle','premium-bundle','Luxury guest experience package: deep cleaning, professional laundry service, premium amenities, quality inspection, 5-star preparation guarantee',70,'bundle','cleaning','job',null,false,null,array['deep-clean','laundry']),
('Office Essentials Plan','office-essentials','Complete office management: weekly cleaning service, supply restocking, maintenance monitoring, professional environment guarantee, flexible scheduling',375,'bundle','cleaning','job',null,false,'monthly',array['light-office','office-restock']),
('Emergency Response Plan','emergency-response','24/7 rapid response service: immediate cleaning/repair dispatch, 2-hour minimum response, priority scheduling, emergency contact support, peace of mind coverage',90,'bundle','repair','job',null,false,null,'{}')
on conflict (slug) do update set
name=excluded.name,description=excluded.description,base_price=excluded.base_price,category=excluded.category,
service_type=excluded.service_type,unit=excluded.unit,market_price=excluded.market_price,is_add_on=excluded.is_add_on,
frequency=excluded.frequency,bundle_services=excluded.bundle_services,active=true;